# Generated by Django 3.0.5 on 2020-04-20 07:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=50, verbose_name='组名')),
                ('group_type', models.IntegerField(default=2, verbose_name='组类型')),
                ('group_info', models.TextField(default='', verbose_name='组描述信息')),
                ('sourcenum', models.IntegerField(default=10, verbose_name='资源数')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'mygroup',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('real_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓名')),
                ('tel', models.TextField(max_length=20, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='部门')),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='创建者')),
                ('role', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '审核员'), (4, '组管理员')], default=1, verbose_name='用户角色')),
                ('user_session_key', models.TextField(default='', verbose_name='记录用户session_key')),
                ('which_group', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='sw_ai_user.MyGroup', verbose_name='用户归属组')),
            ],
            options={
                'db_table': 'myuser',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
