# Generated by Django 3.0.5 on 2020-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='字典名称')),
                ('types', models.SmallIntegerField(choices=[(1, '密码字典'), (2, 'wifi字典'), (3, 'web字典')], default=1, verbose_name='字典类型')),
                ('defaults', models.SmallIntegerField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='默认字典')),
                ('sources', models.SmallIntegerField(choices=[(1, '系统'), (2, '手动')], default=1, verbose_name='字典来源')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('description', models.CharField(max_length=150, verbose_name='字典描述')),
            ],
            options={
                'db_table': 'keyvalue',
            },
        ),
    ]
